### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by d2bugs** [Lunahax/VAL0ADER#1]
### How about a clean video proof of this ?
Is it really working

**Comment by LonelyGuy12** [comment]
I don't think it works after the latest commit on the repo

**Comment by Lunahax** [comment]
Check your compability (winver) or read our faq which can be found on gg/v4l
and read the important notes on the bottom

**Comment by d2bugs** [comment]
Ahhh yeea my windows versions isn't supported 21h2
