### ISSUE TITLE
Unfair Ban

### ISSUE THREAD

**Issue by subliMEgg** [Lunahax/VAL0ADER#6]
dear I was banned from your ds for exposing that valoader modifies the host file and also has Zillya Trojan.Agent.Win32.2853154 Acronis (Static ML) Undetected in version 1.5-f ? 
really?

https://cdn.discordapp.com/attachments/570381703147814912/1018319628876914809/unknown.png

thanks for the clarification

**Comment by Lunahax** [comment]
![Screenshot_20220909-072917_Google.jpg](https://user-images.githubusercontent.com/89605624/189507303-f9dece40-a1f6-4518-870c-5fb1e7f89f1c.jpg)

**Comment by Lunahax** [comment]
![Screenshot_20220909-072917_Google.jpg](https://user-images.githubusercontent.com/89605624/189507303-f9dece40-a1f6-4518-870c-5fb1e7f89f1c.jpg)


fun fact
val0ader 1.5 does not even have a module to edit files as we added local jsons in 1.6

**Comment by Lunahax** [comment]
oh and btw

it wasn't an unfair ban, you violated dc rules lol

**Comment by subliMEgg** [comment]
> oh y por cierto
> 
> no fue una prohibición injusta, violaste las reglas de DC jajaja

How does it violate the rules, so telling people that you are capturing their credit cards and all kinds of sensitive credentials through your program is violating the rules? hahahahaha I mean, is it forbidden in your discord to tell people that you are stealing from them for a cheat in valorant? LOL don't worry RIOT already has the GIT good luck xd with the upcoming bans xd

**Comment by alamarca** [comment]
evil born modified my host file so that the antivirus does not work I had to format my computer and change all the keys that were taken 

https://imgur.com/L71KRbx

**Comment by Lunahax** [comment]
> > oh y por cierto
> > 
> > no fue una prohibición injusta, violaste las reglas de DC jajaja
> 
> How does it violate the rules, so telling people that you are capturing their credit cards and all kinds of sensitive credentials through your program is violating the rules? hahahahaha I mean, is it forbidden in your discord to tell people that you are stealing from them for a cheat in valorant? LOL don't worry RIOT already has the GIT good luck xd with the upcoming bans xd

Bro we don't capture shit
If we would, windows defender or any AV would flag it
And we don't care if Riot has it or not because at least they know we don't steal shit lmao

You're just a mad little kid because you didn't get a key
